Repository AnupK1234/MealMatters, pull requests merged in 2024-01, with the labels that each got.

#14 contact us form api created and integrated
  client/package.json
  client/src/components/Contact.jsx
  client/src/formSchema/ContactUsFormSchema.jsx
  server/app.js
  server/controllers/contactFormController.js
  server/model/Contact.js
Labels: Ready the merge, Accepted

#16 improved documentation
  code_of_conduct.md
Labels: Ready the merge, Accepted

#27 Improve About Us Page UI
  client/src/App.jsx
  client/src/assets/HowItWorks.jpg
  client/src/assets/JoinUs.jpg
  client/src/assets/OurMission.jpg
  client/src/components/About.jsx
Labels: Ready the merge, Accepted

#40 Fix: Home(Logo) Routing
  client/src/components/Navbar.jsx
Labels: Ready the merge, Accepted

#26 Login page CSS done under #12 issue
  client/src/components/Login.jsx
Labels: Ready the merge, Accepted

#46 style:Signup UI enhancement
  client/src/components/Signup.jsx
  client/src/index.css
Labels: Ready to merge, Accepted

#49 Fix why login is showing after user login ( #7)
  client/src/components/Login.jsx
  client/src/components/Navbar.jsx
  client/src/components/Signup.jsx
Labels: Ready to merge, Accepted

#60 feat: add greetings workflow for contributors
  .github/workflows/greetings.yml
Labels: Ready to merge, Accepted

#58 Added docker configurations for MealMatters
  Dockerfile-backend
  Dockerfile-frontend
  client/package.json
  docker-compose.md
  docker-compose.yml
  startup.sh
Labels: Ready to merge, Accepted

#64 Feature/unit and integration testing
  server/app.js
  server/config/connect.js
  server/controllers/auth.js
  server/package-lock.json
  server/package.json
  server/tests/integration/auth.test.js
  server/tests/integration/contact.test.js
  server/tests/integration/product.test.js
  server/tests/unit/middlewares/verifyToken.test.js
Labels: Ready to merge, Accepted, title needs formatting

#65 Make home page responsive and fix nav bar
  client/package-lock.json
  client/src/App.css
  client/src/components/Footer.jsx
  client/src/components/Home.css
  client/src/components/Home.jsx
  client/src/components/Navbar.jsx
  server/package-lock.json
Labels: Ready to merge, Accepted, title needs formatting
