Repository AnupK1234/MealMatters, pull requests merged in 2024-02, with the labels that each got.

#70 fix: #35 - added globalErrorHandling and resolved issue
  server/app.js
  server/middlewares/MongoError.js
  server/middlewares/globalErrorHandlingMiddleware.js
Labels: Ready to merge, Accepted

#71 Change logout button to User avatar with dropdown on hover #69
  client/package-lock.json
  client/src/components/Navbar.jsx
Labels: Accepted, title needs formatting

#78 Fix #76 : Remove the dropdown from Homepage
  client/src/components/Navbar.jsx
Labels: title needs formatting
